# -*- coding: utf-8 -*-
"""Credit_Card_Fraud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aKXrG5r-l-0ZwW2nliu3Q_EeThsl1I5u
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# loading dataset to a pandas Dataframe
credit_card_data = pd.read_csv('/content/creditcard.csv.zip')

# first 5 rows of the dataset
credit_card_data.head()

credit_card_data.tail()

# dataset information
credit_card_data.info()

# checking the number of missing values in each column
credit_card_data.isnull().sum()

# distribution of legit transaction & fraudulent transaction
credit_card_data['Class'].value_counts()

# separating the data fofr analysis
legit = credit_card_data[credit_card_data.Class==0]
fraud = credit_card_data[credit_card_data.Class==1]

print(legit.shape)
print(fraud.shape)

# statistical measure of the data
legit.Amount.describe()

fraud.Amount.describe()

# compare the values for both the transactions
credit_card_data.groupby('Class').mean()



"""Under sampling

Build a sample dataset containing a similar distribution of normal transactions and fraud ones
"""

# No of fraud transactions is 492
legit_sample = legit.sample(n=492)

# concatenating the two datasets
new_dataset = pd.concat([legit_sample, fraud], axis=0) # combining data row wise and not column wise

new_dataset.head()

new_dataset.tail()

new_dataset['Class'].value_counts()

new_dataset.groupby('Class').mean()

# splitting the data into features and targets; Targets means 0 or 1; Features means V1, V2, etc.
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

print(X)

print(Y)

# split the data into training data and testing data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

print(X.shape, X_train.shape, X_test.shape)

# Logistic Regression
model = LogisticRegression()

# training LR model with training data
model.fit(X_train, Y_train)

# Model evaluation and Accuracy Score
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

print('Accuracy on Training Data: ' , training_data_accuracy)

# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

print('Accuracy Score on Test Data:', test_data_accuracy)
